### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by madjin** [takahirox/glTF-Transform-lod-script#2]
Hi, I noticed a small typo on line 203

https://github.com/takahirox/glTF-Transform-lod-script/blob/main/generate_lod.mjs#L203

>           lodOcclusionTexture !== material.getOcculusionTexture()) {

Occulusion should be Occlusion

**Comment by takahirox** [comment]
Thanks for the report. Would you like to make a PR?

**Comment by takahirox** [comment]
Fixed in #3
